config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  devise_for :users
  root 'users#top'
  get 'home/about'
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence:true,length: {maximum: 200}
	validates :body, presence:true,length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  validates :name, length: {in: 2..20},presence:true
  validates :introduction, length: {maximum: 50}
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	  def after_sign_in_path_for(resource)
      user_path(current_user)
  end

   def after_sign_out_path_for(resource)
    root_path
  end


	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name,:email])
		devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, only:[:index,:show,:edit]
	def new
	end
	def create
		@books = Book.all
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		  flash[:notice] = "You have created book successfully"
		  redirect_to book_path(@book.id)
		else
			render "books/index"
		end
	end
	def show
		@book = Book.find(params[:id])
		@user = @book.user
	end
	def index
		@books = Book.all
		@book = Book.new
		@user = User.new
	end
	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end
	def edit
		@book = Book.find(params[:id])
		if @book.id != current_user.id
			redirect_to books_path
		end
	end
	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		  flash[:notice] = "You have update book successfully"
		  redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	private
	def book_params
		params.require(:book).permit(:title,:body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only:[:index,:show,:edit]
	def top
	end

	def new
	end

	def about
	end

	def create
		@user = User.new(user_params)
		if @user.save
		  redirect_to users_path
		else
			render :show
		end
	end

	def index
		@users = User.all
		@book = Book.new
	end

	def show
		@user = User.find(params[:id])
	    @book = Book.new
	    @books = @user.books
	end

	def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
			redirect_to user_path(current_user.id)
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		  flash[:notice] = "You have update user successfully."
		  redirect_to user_path
		else
			render :edit
		end
	end
	private

	def user_params
		params.require(:user).permit(:name,:introduction,:profile_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
  <div class="col-md-offset-3 col-md-6">
	  <h1>Editing Book</h1>

	  <div class="error-format">
    	<% if @book.errors.any? %>
    	  <strong><%= @book.errors.count %>errors prohibited this obj from being saved:</strong><br>
    	  <% @book.errors.full_messages.each do |message| %>
    	      <%= "・#{message}" %><br>
    	      <% end %>
    	    <% end %>
</div>

	  <%= form_for(@book) do |f| %>
		<p>Title</p>
		<%= f.text_field :title,class: "col-md-12" %>
		<p>Opinion</p>
	    <%= f.text_area :body,class: "col-md-12" %><br>
	    <%= f.submit "Update Book",class: "btn btn-primary col-md-12 opinion-margin-bottom" %>
   	  <% end %>
   	  <%= link_to "Show", book_path(@book) %> | <%= link_to "Back",books_path %>
    </div>
 

app/views/books/index.html.erb
<div class="col-md-4">

<div class="error-format">
    	<% if @book.errors.any? %>
    	  <strong><%= @book.errors.count %>errors prohibited this obj from being saved:</strong><br>
    	  <% @book.errors.full_messages.each do |message| %>
    	      <%= "・#{message}" %><br>
    	      <% end %>
    	    <% end %>
</div>

	  <%= render 'layouts/sidebar', user: current_user, book: @book %>
	</div>
  <h1>Books</h1>
  <div class="col-md-8">
    <table class="table table-striped">
	  <tr>
	   	<th></th>
		<th>Title</th>
		<th>Opinion</th>
	  </tr>
  <% @books.each do |book| %>
  	<tr>
	  <td>
	    <%= link_to user_path(book.id) do %>
		<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
		<% end %>
	  </td>
	  <td><%= link_to book.title,book_path(book.id) %></td>
	  <td><%= book.body %></td>
	</tr>
  <% end %>
    </table>
  </div>

app/views/books/show.html.erb
    <div class="col-md-4">
	  <%= render 'layouts/sidebar', user: @user, book: @book %>
	</div>
  <h1>Book detail</h1>
  <div class="col-md-8">
	<table class="table table-striped">
	  <tr>
	    <th>
	      <%= link_to user_path(@book.user_id) do %>
		  <%= attachment_image_tag @user, :profile_image, :fill, 50, 50 %>
		  <%= @book.user.name%>
          <% end %>

        </th>
		<th><%= link_to @book.title,book_path(@book.id) %></th>
		<th><%= @book.body %></th>
		<% if @book.user.id == current_user.id %>
		<th>
			<button type="button" class="btn btn-success"><%= link_to "Edit", edit_book_path(@book.id) %>
			</button>
		</th>
		<th>
			<button type="button" class="btn btn-danger"><%= link_to "Destroy", book_path, method: :delete, data:{confirm: "本当に消しますか？"}, style: "color:white;"%>
			</button>
		</th>
		<% end %>
      </tr>
	  </table>
	</div>

app/views/home/about.html.erb
<div class="container">
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
<p class="col-md-offset-9 col-md-3">CopyRight Infratop.inc</p>
</div>

app/views/layouts/_sidebar.html.erb
	<div class="sidebar">

		<h2>User info</h2>
		<div class="image">
		<%= attachment_image_tag user, :profile_image, :fill, 100, 100,fallback: "no_image.jpg" %>
	    </div>

		<div class="border"></div>
		<div class="row">
			<div class="col-md-3">
			  <p>name</p>
		    </div>
		    <div class="col-md-3">
			  <%= user.name %>
		    </div>
	    </div>

		<div class="border"></div>
	    <div class="row">
	    	<div class="col-md-3">
		      <p>introduction</p>
		    </div>
		    <div class="col-md-3">
		      <%= user.introduction %><br>
		    </div>
		</div>
		<button type="button" class="btn btn-default">
			<%= link_to edit_user_path(user) do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
			<% end %>
		</button>

		<%= form_for(book) do |f| %>

		<h2>New book</h2>

		<p>Title</p>
		<%= f.text_field :title %>

		<p>Opinion</p>
		<%= f.text_area :body %><br>
		<%= f.submit "Create Book",class: "btn btn-primary"%>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
  <nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">

      <div class="navbar-header site-title">
          Bookers
      </div>

      <ul class="nav navbar-nav navbar-right" >
      <% if user_signed_in? %>
        <li class="button">
            <span class="glyphicon glyphicon-home" aria-hidden="true">
          <%= link_to 'Home', user_path(current_user.id),style: "color:gray;" %></span>
        </li>
        <li class="button">
          　<span class="glyphicon glyphicon-user" aria-hidden="true">
          <%= link_to 'Users', users_path,style: "color:gray" %></span>
        </li>
        <li class="button">
          　<span class="glyphicon glyphicon-book" aria-hidden="true">
          <%= link_to 'Books', books_path, style: "color:gray" %></span>
        </li>
        <li class="text-muted">
          　<span class="glyphicon glyphicon-log-out" aria-hidden="true">
          <%= link_to "logout", destroy_user_session_path, method: :delete, style: "color:gray" %></span>
        </li>
        <% else %>
        <li class="button">
          <span class="glyphicon glyphicon-home" aria-hidden="true">
          <%= link_to 'home', root_path, style: "color:gray;" %></span>
        </li>
        <li class="button">
          <span class="glyphicon glyphicon-link" aria-hidden="true">
          <%= link_to 'about', home_about_path, style: "color:gray;" %></span>
        </li>
      <li class="button">
        <span class="glyphicon glyphicon-edit" aria-hidden="true">
        <%= link_to "sign up", new_user_registration_path, style: "color:gray;" %></span>
      </li>
      <li class="button">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true">
        <%= link_to "login", new_user_session_path, style: "color:gray;" %></span>
      </li>
      <% end %>
      </ul>
  </div>
</nav>

</div>
    </header>

<div class="container">
  <div class="row">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
    <%= yield %>
  </div>
</div>
<p class="col-md-offset-9 col-md-3">CopyRight Infratop.inc</p>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
<h1>User info</h1>

<div class="error-format">
    	<% if @user.errors.any? %>
    	  <strong><%= @user.errors.count %>errors prohibited this obj from being saved:</strong><br>
    	  <% @user.errors.full_messages.each do |message| %>
    	      <%= "・#{message}" %><br>
    	      <% end %>
    	    <% end %>
</div>

<p>Name</p><%= f.text_field :name %>
<p>Image</p><%= f.attachment_field :profile_image %>
<p>Introduction</p><%= f.text_area :introduction %>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
    <div class="col-md-4">
	  <%= render 'layouts/sidebar', user: current_user, book: @book %>
	</div>
  <h1>Users</h1>
  <div class="col-md-8">
    <table class="table table-striped">
	  <tr>
	    <th>image</th>
		<th>name</th>
		<th></th>
	  </tr>
  <% @users.each do |user| %>
	<tr>
		<td>
			<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50'  %>
		</td>
		<td><%= user.name %></td>
		<td><%= link_to "Show",user_path(user.id) %></td>
	</tr>
  <% end %>
    </table>

app/views/users/show.html.erb
    <div class="col-md-4">
	  <%= render 'layouts/sidebar', user: @user, book: @book %>
	</div>
  <h1>Books</h1>
  <div class="col-md-8">
	<table class="table table-striped">
	  <tr>
	    <th></th>
		<th>Title</th>
		<th>Opinion</th>
      </tr>

  <% @books.each do |book| %>
    <tr>
	  <td>
	    <%= link_to user_path(@user.id) do %>
		  <%= attachment_image_tag @user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg" %>
        <% end %>
	  </td>
	  <td><%= link_to book.title,book_path(book.id) %></td>
	  <td><%= book.body %></td>
	</tr>
  <% end %>
	  </table>
	</div>

app/views/users/top.html.erb
  <div class="top-page-box col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers  !!</h1>
    <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><b>Bookers,</b></p>
    <p class="line-height">
      you can share and exchange your opinions , inpressions , and emotions<br>
      about varioius books!
    </p>
    <div class="row">
	  <button type="button" class="btn btn-info col-md-offset-1 col-md-10"><%= link_to "Log in",new_user_session_path %></button>
    </div>
    <div class="row">
	  <button type="button" class="btn btn-success col-md-offset-1 col-md-10"><%= link_to "Sign up",new_user_registration_path%></button>
    </div>
  </div>